### PR TITLE
Add feature to read from json conf files

### PR DESCRIPTION
**Pull request by akhillb**
Reads from a json file with all the required parameters as required by Browserstack.

### CODE REVIEW

**Comment by bennylope** [comment]
Cool, thanks!

**Comment by akhillb** [comment]
Should i send a PR updating the readme also?

**Comment by bennylope** [comment]
Yeah, if you do that I'll merge it in and then bump the version for a Rubygems update.

**Comment by bennylope** [comment]
Closes #7

**Pull request merged**
